"""Provider-agnostic prompt/styling toolkit for LLM-powered git workflows."""

from ._generate import (
    BODY_WRAP_WIDTH,
    SUBJECT_LIMIT,
    SubjectTrim,
    build_commit_prompt,
    build_mr_prompt,
    enforce_subject_limit,
    parse_commit_response,
    parse_mr_response,
    strip_fences,
    wrap_commit_body,
)
from ._git import (
    check_git_repo,
    derive_diff_stat,
    format_commit_log,
    get_commit_log,
    get_current_branch,
    get_diff,
    get_diff_stat,
    get_git_dir,
    get_head_sha,
    get_mr_release_context,
    get_release_context,
    get_staged_diff,
)
from ._git_branch import (
    branch_content_id,
    format_branch_context,
    get_branch_churn_subjects,
    get_branch_commit_subjects,
    get_default_branch,
    resolve_commit_base,
)
from ._instructions import format_repo_guidance, load_repo_instructions
from ._pr_incremental import (
    RepoPrContext,
    load_cached_content_id,
    load_cached_pr,
    load_cached_pr_sha,
    prepare_repo_pr_context,
    prune_pr_cache,
    save_cached_pr,
)
from ._pr_prompt_build import DiffScope
from ._pr_render import render_pr_diff, summarize_pr_changes
from ._scope import (
    MAX_SCOPE_COMMITS,
    BranchScope,
    Concern,
    ScopeCommit,
    analyze_branch_scope,
    suggested_split,
)

__all__ = [
    "BODY_WRAP_WIDTH",
    "MAX_SCOPE_COMMITS",
    "SUBJECT_LIMIT",
    "BranchScope",
    "Concern",
    "DiffScope",
    "RepoPrContext",
    "ScopeCommit",
    "SubjectTrim",
    "analyze_branch_scope",
    "branch_content_id",
    "build_commit_prompt",
    "build_mr_prompt",
    "check_git_repo",
    "derive_diff_stat",
    "enforce_subject_limit",
    "format_branch_context",
    "format_commit_log",
    "format_repo_guidance",
    "get_branch_churn_subjects",
    "get_branch_commit_subjects",
    "get_commit_log",
    "get_current_branch",
    "get_default_branch",
    "get_diff",
    "get_diff_stat",
    "get_git_dir",
    "get_head_sha",
    "get_mr_release_context",
    "get_release_context",
    "get_staged_diff",
    "load_cached_content_id",
    "load_cached_pr",
    "load_cached_pr_sha",
    "load_repo_instructions",
    "parse_commit_response",
    "parse_mr_response",
    "prepare_repo_pr_context",
    "prune_pr_cache",
    "render_pr_diff",
    "resolve_commit_base",
    "save_cached_pr",
    "strip_fences",
    "suggested_split",
    "summarize_pr_changes",
    "wrap_commit_body",
]
